client_id = "97158f85dddff262f2fced9d6321ecf7"
name = "Section Master"
application_url = "https://custom-sections-app-v2.vercel.app"
embedded = true
handle = "custom-sections-app-v2"

[webhooks]
api_version = "2023-10"

[access_scopes]
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [ "https://custom-sections-app-v2.vercel.app/auth/callback" ]

[pos]
embedded = true

[build]
automatically_update_urls_on_dev = true
