# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97158f85dddff262f2fced9d6321ecf7"
name = "Section Master"
application_url = "https://custom-sections-app-v2.vercel.app"
embedded = true
handle = "custom-sections-app-v2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2023-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://custom-sections-app-v2.vercel.app/auth/callback" ]

[pos]
embedded = true
